'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.488
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Namespace My


	<Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(), Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")> _
	Friend NotInheritable Partial Class Settings
		Inherits System.Configuration.ApplicationSettingsBase

		Private Shared defaultInstance As Settings = (CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New Settings()), Settings))

		Public Shared ReadOnly Property [Default]() As Settings
			Get
				Return defaultInstance
			End Get
		End Property

		<Global.System.Configuration.UserScopedSettingAttribute(), Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.Configuration.DefaultSettingValueAttribute("4530")> _
		Public Property ColorPort() As Integer
			Get
				Return (CInt(Fix(Me("ColorPort"))))
			End Get
			Set(ByVal value As Integer)
				Me("ColorPort") = value
			End Set
		End Property

		<Global.System.Configuration.UserScopedSettingAttribute(), Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.Configuration.DefaultSettingValueAttribute("4531")> _
		Public Property DepthPort() As Integer
			Get
				Return (CInt(Fix(Me("DepthPort"))))
			End Get
			Set(ByVal value As Integer)
				Me("DepthPort") = value
			End Set
		End Property

		<Global.System.Configuration.UserScopedSettingAttribute(), Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.Configuration.DefaultSettingValueAttribute("4532")> _
		Public Property SkeletonPort() As Integer
			Get
				Return (CInt(Fix(Me("SkeletonPort"))))
			End Get
			Set(ByVal value As Integer)
				Me("SkeletonPort") = value
			End Set
		End Property

		<Global.System.Configuration.UserScopedSettingAttribute(), Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.Configuration.DefaultSettingValueAttribute("4533")> _
		Public Property AudioPort() As Integer
			Get
				Return (CInt(Fix(Me("AudioPort"))))
			End Get
			Set(ByVal value As Integer)
				Me("AudioPort") = value
			End Set
		End Property
	End Class
End Namespace
